import CourseImages from './Photo.js';

export const popularCourses = [
    {
        id: 1,
        title: 'React Basics',
        description: 'Master the fundamentals of React.js with this comprehensive course. Explore React components, state management, and hooks, and apply your knowledge to real-world projects.',
        instructor: 'John Doe',
        price: 49.99,
        imageSrc: CourseImages.first,
    },
    {
        id: 2,
        title: 'Advanced JavaScript',
        description: 'Dive deep into advanced JavaScript concepts. Cover topics such as closures, promises, and asynchronous programming.',
        instructor: 'Jane Smith',
        price: 59.99,
        imageSrc: CourseImages.second,
    },
    {
        id: 3,
        title: 'Introduction to Python',
        description: 'Explore the basics of Python programming language. Learn about data types, loops, and functions.',
        instructor: 'Alex Johnson',
        price: 39.99,
        imageSrc: CourseImages.third,
    },
    {
        id: 4,
        title: 'Data Science with R',
        description: 'Take an in-depth course on data science using the R language. Cover data manipulation, visualization, and statistical analysis.',
        instructor: 'Emily Davis',
        price: 79.99,
        imageSrc: CourseImages.fourth,
    },
];

export const newCourses = [
    {
        id: 1,
        title: 'Web Development Fundamentals',
        description: 'Build a solid foundation in web development and coding. Cover HTML, CSS, and JavaScript basics with hands-on exercises.',
        instructor: 'Michael Brown',
        price: 29.99,
        imageSrc: CourseImages.fifth,
    },
    {
        id: 2,
        title: 'Machine Learning for Beginners',
        description: 'Get an introduction to machine learning and its applications. Explore supervised and unsupervised learning.',
        instructor: 'Sophie Turner',
        price: 69.99,
        imageSrc: CourseImages.sixth,
    },
    {
        id: 3,
        title: 'Introduction to UX Design',
        description: 'Explore the principles of User Experience (UX) design. Cover usability, wireframing, and prototyping.',
        instructor: 'Olivia Miller',
        price: 49.99,
        imageSrc: CourseImages.seventh,
    },
    {
        id: 4,
        title: 'Blockchain Fundamentals',
        description: 'Dive into the world of blockchain technology. Learn about decentralized systems, smart contracts, and cryptocurrency.',
        instructor: 'Daniel White',
        price: 99.99,
        imageSrc: CourseImages.eighth,
    },
    {
        id: 5,
        title: 'Cybersecurity Essentials',
        description: 'Enhance your understanding of cybersecurity. Explore essential concepts, tools, and practices to secure digital systems.',
        instructor: 'Ava Martinez',
        price: 79.99,
        imageSrc: CourseImages.nineth,
    },
    {
        id: 6,
        title: 'Full Stack Web Development',
        description: 'Become a Full Stack Developer and learn how to build web applications from front to back.',
        instructor: 'David Johnson',
        price: 89.99,
        imageSrc: CourseImages.tenth,
    },
    {
        id: 7,
        title: 'Mobile App Development with React Native',
        description: 'Explore mobile app development using React Native.',
        instructor: 'Sophia Garcia',
        price: 69.99,
        imageSrc: CourseImages.eleventh,
    },
];
